version: '3.7'

services:
    postgres:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgresdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

volumes:
    postgresdata:
